# Generated by Django 4.2.5 on 2023-09-28 10:07

import apps.account.managers
import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_data_joined_account_date_joined'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', apps.account.managers.AccountManager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=20, validators=[apps.account.models.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=20, validators=[apps.account.models.validate_name], verbose_name='last_name'),
        ),
    ]
