# Generated by Django 4.2.5 on 2023-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
