# Generated by Django 4.2.5 on 2023-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_designation_name_alter_services_service_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designation'},
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
