# Generated by Django 4.2.5 on 2023-10-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_banks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Bank'},
        ),
    ]
