# Generated by Django 4.2.5 on 2023-10-02 11:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('client_name', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('state_govt', 'State Govt'), ('central_govt', 'Central Govt'), ('private', 'Private')], max_length=20)),
                ('client_gst', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_singed', models.DateField(blank=True, null=True)),
                ('contract_period', models.DateTimeField(blank=True, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_address', models.TextField(blank=True, null=True)),
                ('client_city', models.CharField(blank=True, max_length=50, null=True)),
                ('client_pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('client_tenture_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active_status', models.BooleanField(default=True)),
                ('designation', models.ManyToManyField(blank=True, related_name='client_designations', to='general.designation')),
                ('service', models.ManyToManyField(blank=True, related_name='client_services', to='general.services')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
    ]
