# Generated by Django 4.2.5 on 2023-11-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_type',
            field=models.CharField(choices=[('sq_feet', 'Sq Feet'), ('man_power', 'Man Power')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
