# Generated by Django 4.2.5 on 2023-11-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_logo',
            field=models.ImageField(default='default_logo', upload_to='client_logos'),
        ),
    ]
