# Generated by Django 4.2.5 on 2023-11-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_logo',
            field=models.ImageField(default='default_logo.jpg', upload_to='client_logos'),
        ),
    ]
