# Generated by Django 4.2.5 on 2023-10-05 10:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_alter_designation_options_designation_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(db_index=True, max_length=15, unique=True)),
                ('whatsappNum', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('uanNumber', models.CharField(max_length=20, unique=True)),
                ('aadhar', models.CharField(max_length=20, unique=True)),
                ('pan_card', models.CharField(blank=True, max_length=30, null=True)),
                ('esiNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateTimeField()),
                ('profile_img', models.ImageField(blank=True, upload_to='images/user_profile/')),
                ('pcc_image', models.ImageField(blank=True, upload_to='images/emp_pcc/')),
                ('aadhar_image', models.ImageField(blank=True, upload_to='images/emp_aadhar/')),
                ('bank_passbook', models.ImageField(blank=True, upload_to='images/emp_passbook')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='general.designation')),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employess',
            },
        ),
    ]
