# Generated by Django 4.2.5 on 2023-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
