# Generated by Django 4.2.5 on 2023-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_current_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='emp_aadhar/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_passbook',
            field=models.ImageField(blank=True, null=True, upload_to='emp_passbook/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pcc_image',
            field=models.ImageField(blank=True, null=True, upload_to='emp_pcc/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone_no', 'aadhar', 'esiNumber'], name='employees_e_phone_n_687ae0_idx'),
        ),
    ]
