# Generated by Django 4.2.5 on 2023-11-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_rename_account_number_employeebank_accountnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_actice',
            field=models.BooleanField(default=True),
        ),
    ]
